#pragma once

#define ID_LIB                                3
#define IDM_REQUEST_OBJECT                    4
#define IDC_CHECK_AUTO                        2000
#define IDC_CHECK_MESSAGE                     2001
#define IDD_DIALOG_CFG                        2001
#define IDC_CHECK_MESSAGE_APP                 2001
#define IDC_CHECK_PARAM                       2002
#define IDC_CHECK_MESSAGE_STAMP               2002
#define IDC_CHECK_MESSAGE_DOC                 2003
#define IDC_CHECK_MESSAGE_SPCDOC              2004
#define IDC_CHECK_MESSAGE_2DDOC               2005
#define IDC_CHECK_MESSAGE_OBJ_2DDOC           2006
#define IDC_CHECK_MESSAGE_SPC                 2007
#define IDC_CHECK_MESSAGE_SELECT              2008
#define IDC_CHECK_MESSAGE_OBJ_3DDOC           2009
#define IDC_CHECK_MESSAGE_OBJ_SPC             2010
#define IDC_CHECK_MESSAGE_3DDOC               2011
#define IDS_ADVISE_FAIL                       2012
#define IDS_ADVISE_OK                         2013
#define IDS_UNADVISE                          2014
#define IDS_ADVISE_EXISTS                     2015
#define IDS_ADVISE_NOT_FOUND                  2016
#define IDS_ADVISE_LIST                       2017
#define IDS_TYPE_DOC                          2018
#define IDS_ADVISE_APP                        2019
#define IDS_APP_BEGIN_CREATE_QUESTION1        2020
#define IDS_APP_BEGIN_CREATE_QUESTION2        2021
#define IDS_APP_BEGIN_OPEN_QUESTION           2022
#define IDS_APP_BEGIN_REQUEST_FILES           2023
#define IDS_APP_CLOSE_ALL                     2024
#define IDS_APP_BEGIN_CHOICEMATERIAL_QUESTION 2025
#define IDS_ERROR_CODE                        2026
#define IDS_DOC_DOC                           2027
#define IDS_DOC_DRAWING                       2028
#define IDS_DOC_FRAGMENT                      2029
#define IDS_DOC_PART                          2030
#define IDS_DOC_ASSEMBLY                      2031
#define IDS_DOC_SPC                           2032
#define IDS_DOC_TXT                           2033
#define IDS_ADVISE_DOC                        2034
#define IDS_UNADVISE_DOC                      2035
#define IDS_UNADVISE_DOC_FAIL                 2036
#define IDS_NO_ACTIVE_DOC                     2037
#define IDS_DOC_SAVE                          2038
#define IDS_DOC_AUTOSAVE                      2039
#define IDS_DOC_CLOSE                         2040
#define IDS_DOC_BEGIN_SAVE_QUESTION           2050
#define IDS_ADVISE_DOC_FRAME                  2051
#define IDS_UNADVISE_DOC_FRAME                2052
#define IDS_ADVISE_DOC_FRAME_QUESTION         2053
#define IDS_ADVISE_DOC_2D                     2054
#define IDS_UNADVISE_DOC_2D                   2055
#define IDS_UNADVISE_DOC_2D_FAIL              2056
#define IDS_ADVISE_DOC_3D                     2057
#define IDS_UNADVISE_DOC_3D                   2058
#define IDS_UNADVISE_DOC_3D_FAIL              2059
#define IDS_NO_ACTIVE_DOC_3D                  2060
#define IDS_DOC_REBUILD                       2061
#define IDS_CHANGE_MATERIAL                   2062
#define IDS_DELETE_MATERIAL                   2063
#define IDS_CHANGE_MARKING                    2064
#define IDS_CHOICE_PROPERTY                   2065
#define IDS_DELETE_PROPERTY                   2066
#define IDS_INSERT_FRAGMENT                   2067
#define IDS_SETPART_FROMFILE                  2068
#define IDS_CREATE_PART                       2069
#define IDS_ROLL_BACK                         2070
#define IDS_LOAD_COMBINATION_CHANGE           2071
#define IDS_ADVISE_OBJECT_2D                  2072
#define IDS_UNADVISE_OBJECT_2D                2073
#define IDS_OBJECT_2D_ADVISED_TYPE            2074
#define IDS_NO_ACTIVE_DOC_2D                  2075
#define IDS_OBJECT_TYPES                      2076
#define IDS_OBJECT_TYPE                       2077
#define IDS_OBJECT_DELETE                     2078
#define IDS_OBJECT_MOVE                       2079
#define IDS_OBJECT_ROTATE                     2080
#define IDS_OBJECT_SCALE                      2081
#define IDS_OBJECT_TRANSFORM                  2082
#define IDS_OBJECT_COPY                       2083
#define IDS_OBJECT_SYMMETRY                   2084
#define IDS_OBJECT_CHANGED                    2085
#define IDS_BEGIN_PROCESS                     2086
#define IDS_UNADVISE_FAIL                     2087
#define IDS_OBJECT_2D_ADVISED_OJECT           2088
#define IDS_ADVISE_SELECTION_MANAGER          2089
#define IDS_UNADVISE_SELECTION_MANAGER        2090
#define IDS_ADVISE_STAMP                      2091
#define IDS_UNADVISE_STAMP                    2092
#define IDS_STAMP_BEGIN_EDIT                  2093
#define IDS_STAMP_CELL_DBLCLICK               2094
#define IDS_STAMP_CELL_EDIT                   2095
#define IDS_STAMP_CELL_DBLCLICK_STR           2096
#define IDS_STAMP_CELL_EDIT_STR               2097
#define IDS_WRONG_DOCTYPE                     2098
#define IDS_ADVISE_OBJECT_3D                  2099
#define IDS_UNADVISE_OBJECT_3D                2100
#define IDS_OBJECT_3D_ADVISED_TYPE            2101
#define IDS_UNADVISE_ALL_OBJ_3D               2102
#define IDS_EXCLUDED_OBJ                      2103
#define IDS_INCLUDED_OBJ                      2104
#define IDS_HIDDEN_OBJ                        2105
#define IDS_SHOWN_OBJ                         2106
#define IDS_CHANGE_PLACEMENT                  2107
#define IDS_ADVISE_SPC_OBJ                    2108
#define IDS_UNADVISE_SPC_OBJ                  2109
#define IDS_SPC_ADD_DOC                       2110
#define IDS_SPC_CHANGE_GEOM                   2111
#define IDS_SPC_CELL_EDIT                     2112
#define IDS_SPC_OBJ_EDIT                      2113
#define IDS_SPC_NO_OBJ                        2114
#define IDS_SPC_WRONG_DOC_TYPE                2115
#define IDS_ADVISE_PART_OR_FEATURE            2116
#define IDS_SPC_DOC_ADD_DOC                   2117
#define IDS_SPC_DOC_REMOVE_DOC                2118
#define IDS_SPC_DOC_CHANGE_STYLE              2119
#define IDS_ADVISE_SPC_DOC                    2120
#define IDS_UNADVISE_SPC_DOC                  2121
#define IDS_NO_ACTIVE_DOC_SPC                 2122
#define IDS_ADVISE_SPC_DESCR                  2123
#define IDS_UNADVISE_SPC_DESCR                2124
#define IDS_SPC_DESCR_EDIT                    2125
#define IDS_SPC_DESCR_CALC_POS                2126
#define IDS_SPC_DESCR_CREATE                  2127
#define IDS_INI_NOT_EXISTS                    2128
#define IDS_INI_READ_FAIL                     2129
#define IDS_INI_WRITE_FAIL                    2130
#define IDS_INI_SECTION_CFG                   2131
#define IDS_INI_KEY_AUTOADVISE                2132
#define IDS_INI_KEY_MESS_DOC2D                2133
#define IDS_INI_KEY_MESS_DOC3D                2134
#define IDS_INI_KEY_MESS_APP                  2135
#define IDS_INI_KEY_MESS_DOCS                 2136
#define IDS_INI_KEY_MESS_OBJDOC2D             2137
#define IDS_INI_KEY_MESS_OBJDOC3D             2138
#define IDS_INI_KEY_MESS_OBJSPC               2139
#define IDS_INI_KEY_MESS_SELECT               2140
#define IDS_INI_KEY_MESS_SPCDESCR             2141
#define IDS_INI_KEY_MESS_SPCDOC               2142
#define IDS_INI_KEY_MESS_STAMP                2143
#define IDS_INI_KEY_MESS_DOCFRAME             2144
#define IDS_ADVISED_TYPES                     2145
#define IDS_ADVISED_OBJECTS                   2146
#define IDS_SELECT_OBJECTS                    2147
#define IDS_SELECT_OBJECTS_FOR_ADVISE         2148
#define IDS_ENTER_OBJ_TYPE_NUM                2149
#define IDS_ENTER_VIEW_NUM                    2150
#define IDS_VIEW_NOT_EXISTS                   2151
#define IDS_ENTER_LAYER_NUM                   2152
#define IDS_LAYER_NOT_EXISTS                  2153
#define IDS_CHOOSE_OTHER_TYPE                 2154

// from D:\SVN\SDK\Include\ldefin2d.h
#define SPC_BASE_OBJECT 1
#define SPC_COMMENT     2

// События Компаса
#define POPUP_APP_EVENTS 101
#define CMP_APP_ADVISE   10
#define CMP_APP_UNADVISE 11

// События документов
#define POPUP_DOC_EVENTS 200
#define CMP_DOC_ADVISE   20
#define CMP_DOC_UNADVISE 21

//События 2D документов
#define POPUP_DOC_2D_EVENTS 210
#define CMP_DOC_2D_ADVISE   22
#define CMP_DOC_2D_UNADVISE 23

// События объектов 2D документа
#define POPUP_OBJECT_2D_EVENTS     310
#define CMP_OBJECT_2D_ADVISE       30
#define CMP_OBJECT_2D_UNADVISE     31
#define CMP_ADVISE_VIEW_BY_NUM     32
#define CMP_UNADVISE_VIEW_BY_NUM   33
#define CMP_ADVISE_LAYER_BY_NUM    34
#define CMP_UNADVISE_LAYER_BY_NUM  35
#define CMP_OBJECT_2D_UNADVISE_ALL 36

// События селектирования
#define POPUP_SELECTION_MNG_EVENTS 410
#define CMP_SELECTION_MNG_ADVISE   40
#define CMP_SELECTION_MNG_UNADVISE 41

// События штампа
#define POPUP_STAMP_EVENTS 5000
#define CMP_STAMP_ADVISE   50
#define CMP_STAMP_UNADVISE 51

// События 3D документов
#define POPUP_DOC_3D_EVENTS 600
#define CMP_DOC_3D_ADVISE   60
#define CMP_DOC_3D_UNADVISE 61

// События объектов 3D документов
#define POPUP_OBJECT_3D_EVENTS            7000
#define POPUP_OBJECT_3D_ADVISE            7001
#define CMP_OBJECT_3D_ADVISE_SELECT       70
#define CMP_ADVISE_O3D_UNKNOWN            500
#define CMP_ADVISE_O3D_PLANEXOY           501
#define CMP_ADVISE_O3D_PLANEXOZ           502
#define CMP_ADVISE_O3D_PLANEYOZ           503
#define CMP_ADVISE_O3D_POINTCS            504
#define CMP_ADVISE_O3D_SKETCH             505
#define CMP_ADVISE_O3D_AXIS2PLANES        509
#define CMP_ADVISE_O3D_AXIS2POINTS        510
#define CMP_ADVISE_O3D_AXISCONEFACE       511
#define CMP_ADVISE_O3D_AXISEDGE           512
#define CMP_ADVISE_O3D_AXISOPERATION      513
#define CMP_ADVISE_O3D_PLANEOFFSET        514
#define CMP_ADVISE_O3D_PLANEANGLE         515
#define CMP_ADVISE_O3D_PLANE3POINTS       516
#define CMP_ADVISE_O3D_PLANENORMAL        517
#define CMP_ADVISE_O3D_PLANETANGENT       518
#define CMP_ADVISE_O3D_PLANEEDGEPOINT     519
#define CMP_ADVISE_O3D_PLANEPARALLEL      520
#define CMP_ADVISE_O3D_PLANEPERPENDICULAR 521
#define CMP_ADVISE_O3D_PLANELINETOEDGE    522
#define CMP_ADVISE_O3D_PLANELINETOPLANE   523
#define CMP_ADVISE_O3D_BOSSEXTRUSION      525
#define CMP_ADVISE_O3D_CUTEXTRUSION       526
#define CMP_ADVISE_O3D_BOSSROTATED        528
#define CMP_ADVISE_O3D_CUTROTATED         529
#define CMP_ADVISE_O3D_BOSSLOFT           531
#define CMP_ADVISE_O3D_CUTLOFT            532
#define CMP_ADVISE_O3D_CHAMFER            533
#define CMP_ADVISE_O3D_FILLET             534
#define CMP_ADVISE_O3D_MESHCOPY           535
#define CMP_ADVISE_O3D_CIRCULARCOPY       536
#define CMP_ADVISE_O3D_CURVECOPY          537
#define CMP_ADVISE_O3D_CIRCPARTARRAY      538
#define CMP_ADVISE_O3D_MESHPARTARRAY      539
#define CMP_ADVISE_O3D_CURVEPARTARRAY     540
#define CMP_ADVISE_O3D_DERIVPARTARRAY     541
#define CMP_ADVISE_O3D_INCLINE            542
#define CMP_ADVISE_O3D_SHELLOPERATION     543
#define CMP_ADVISE_O3D_RIBOPERATION       544
#define CMP_ADVISE_O3D_BOSSEVOLUTION      546
#define CMP_ADVISE_O3D_CUTEVOLUTION       547
#define CMP_ADVISE_O3D_MIRROROPERATION    548
#define CMP_ADVISE_O3D_MIRRORALLOPERATION 549
#define CMP_ADVISE_O3D_CUTBYPLANE         550
#define CMP_ADVISE_O3D_CUTBYSKETCH        551
#define CMP_ADVISE_O3D_HOLEOPERATION      552
#define CMP_ADVISE_O3D_POLYLINE           553
#define CMP_ADVISE_O3D_CONICSPIRAL        554
#define CMP_ADVISE_O3D_SPLINE             555
#define CMP_ADVISE_O3D_CYLINDRICSPIRAL    556
#define CMP_ADVISE_O3D_IMPORTEDSURFACE    557
#define CMP_ADVISE_O3D_THREAD             558
#define CMP_ADVISE_O3D_PART               604
#define CMP_ADVISE_O3D_FEATURE            620

#define POPUP_OBJECT_3D_UNADVISE            7002
#define CMP_OBJECT_3D_UNADVISE_SELECT       80
#define CMP_UNADVISE_O3D_UNKNOWN            700
#define CMP_UNADVISE_O3D_PLANEXOY           701
#define CMP_UNADVISE_O3D_PLANEXOZ           702
#define CMP_UNADVISE_O3D_PLANEYOZ           703
#define CMP_UNADVISE_O3D_POINTCS            704
#define CMP_UNADVISE_O3D_SKETCH             705
#define CMP_UNADVISE_O3D_AXIS2PLANES        709
#define CMP_UNADVISE_O3D_AXIS2POINTS        710
#define CMP_UNADVISE_O3D_AXISCONEFACE       711
#define CMP_UNADVISE_O3D_AXISEDGE           712
#define CMP_UNADVISE_O3D_AXISOPERATION      713
#define CMP_UNADVISE_O3D_PLANEOFFSET        714
#define CMP_UNADVISE_O3D_PLANEANGLE         715
#define CMP_UNADVISE_O3D_PLANE3POINTS       716
#define CMP_UNADVISE_O3D_PLANENORMAL        717
#define CMP_UNADVISE_O3D_PLANETANGENT       718
#define CMP_UNADVISE_O3D_PLANEEDGEPOINT     719
#define CMP_UNADVISE_O3D_PLANEPARALLEL      720
#define CMP_UNADVISE_O3D_PLANEPERPENDICULAR 721
#define CMP_UNADVISE_O3D_PLANELINETOEDGE    722
#define CMP_UNADVISE_O3D_PLANELINETOPLANE   723
#define CMP_UNADVISE_O3D_BOSSEXTRUSION      725
#define CMP_UNADVISE_O3D_CUTEXTRUSION       726
#define CMP_UNADVISE_O3D_BOSSROTATED        728
#define CMP_UNADVISE_O3D_CUTROTATED         729
#define CMP_UNADVISE_O3D_BOSSLOFT           731
#define CMP_UNADVISE_O3D_CUTLOFT            732
#define CMP_UNADVISE_O3D_CHAMFER            733
#define CMP_UNADVISE_O3D_FILLET             734
#define CMP_UNADVISE_O3D_MESHCOPY           735
#define CMP_UNADVISE_O3D_CIRCULARCOPY       736
#define CMP_UNADVISE_O3D_CURVECOPY          737
#define CMP_UNADVISE_O3D_CIRCPARTARRAY      738
#define CMP_UNADVISE_O3D_MESHPARTARRAY      739
#define CMP_UNADVISE_O3D_CURVEPARTARRAY     740
#define CMP_UNADVISE_O3D_DERIVPARTARRAY     741
#define CMP_UNADVISE_O3D_INCLINE            742
#define CMP_UNADVISE_O3D_SHELLOPERATION     743
#define CMP_UNADVISE_O3D_RIBOPERATION       744
#define CMP_UNADVISE_O3D_BOSSEVOLUTION      746
#define CMP_UNADVISE_O3D_CUTEVOLUTION       747
#define CMP_UNADVISE_O3D_MIRROROPERATION    748
#define CMP_UNADVISE_O3D_MIRRORALLOPERATION 749
#define CMP_UNADVISE_O3D_CUTBYPLANE         750
#define CMP_UNADVISE_O3D_CUTBYSKETCH        751
#define CMP_UNADVISE_O3D_HOLEOPERATION      752
#define CMP_UNADVISE_O3D_POLYLINE           753
#define CMP_UNADVISE_O3D_CONICSPIRAL        754
#define CMP_UNADVISE_O3D_SPLINE             755
#define CMP_UNADVISE_O3D_CYLINDRICSPIRAL    756
#define CMP_UNADVISE_O3D_IMPORTEDSURFACE    757
#define CMP_UNADVISE_O3D_THREAD             758
#define CMP_UNADVISE_O3D_PART               804
#define CMP_UNADVISE_O3D_FEATURE            820
#define CMP_OBJECT_3D_UNADVISE_ALL          90


// События объекта спецификации
#define POPUP_SPC_OBJ_EVENTS     7003
#define POPUP_SPC_OBJ_ADVISE     7013
#define CMP_SPC_ADVISE_CURRENT   100
#define CMP_SPC_ADVISE_ALL       300
#define CMP_SPC_ADVISE_BASE      301
#define CMP_SPC_ADVISE_COMMENT   302
#define POPUP_SPC_OBJ_UNADVISE   7023
#define CMP_SPC_UNADVISE_CURRENT 110
#define CMP_SPC_UNADVISE_ALL     400
#define CMP_SPC_UNADVISE_BASE    401
#define CMP_SPC_UNADVISE_COMMENT 402


// События документа спецификации
#define POPUP_SPC_DOC_EVENTS 7004
#define CMP_SPC_DOC_ADVISE   130
#define CMP_SPC_DOC_UNADVISE 131

// События спецификации
#define POPUP_SPC_EVENTS 7005
#define CMP_SPC_ADVISE   140
#define CMP_SPC_UNADVISE 141

#define CMP_SNAPSHOT            996
#define CMP_LIST_EVENTS         997
#define CMP_UNADVISE_ALL_EVENTS 998
#define CMP_CONFIG              999
