#pragma once

// Autogenerated include files. Do not edit!!!
#if defined(__cplusplus) && !defined(DONT_USE_GENERATED_PCH)
// clang-format off
#include <KsAPI/Impl/KsApiUtils.h>
#include <KsAPI/Impl/Common/KsApiKompasDictionary.h>
#include <KsAPI/Impl/Common/KsApiUserParameters.h>
#include <KsAPI/Impl/Common/KsApiVariableTable.h>
#include <KsAPI/Impl/Documents/KsApiKompasDocument.h>
#include <KsAPI/Impl/Objects/2D/KsApiBaseLeader.h>
#include <KsAPI/Impl/Objects/2D/KsApiDrawingObjects.h>
#include <KsAPI/Impl/Objects/3D/KsApiBaseDesignation3D.h>
#include <KsAPI/Impl/Objects/3D/KsApiBaseDimension3DWithParams.h>
#include <KsAPI/Impl/Objects/3D/KsApiFeaturePattern.h>
#include <KsAPI/Impl/Objects/3D/KsApiLocalCoordinateSystem.h>
#include <KsAPI/Impl/Objects/3D/KsApiModelCurve3D1.h>
#include <KsAPI/Impl/Objects/3D/KsApiModelLCSObject.h>
#include <KsAPI/Impl/Objects/3D/KsApiThinParameters.h>
#include <KsAPI/Impl/Processes/KsApiPropertyControl.h>
#include <API2DCore/API2DCore.h>
#include <API2DCore/ControlValue.h>
#include <API2DCore/IAPI2DObjects.h>
#include <API2DCore/IAPILeaders.h>
#include <API2DCore/IAPIPropertyMng.h>
#include <API2DCore/IAPISpecification.h>
#include <API2DCore/IAPITable.h>
#include <API2DCore/IAPIVariables.h>
#include <API2DCore/IApplication.h>
//#include <API2DCore/ISelfDocuments.h>
#include <API3DCore/IAPIDefinitions3D.h>
// clang-format on
#endif // __cplusplus
// Autogenerated include files. Do not edit!!!
