#include "Step2_KsAPI_2D_pch.h"

#include "Resource.h"

static ksapi::IResourcesModulePtr resourceModule;
std::wstring libname = L"Step2_KsAPI_2D";

void * GetModule()
{
  return &resourceModule;
}

#define MENU_ID(idName)   resourceModule->AddMenuId(L"" #idName, idName);
#define STRING_ID(idName) resourceModule->AddStringId(L"" #idName, idName);

void LoadResources(ksapi::IApplication & app)
{
  resourceModule = app.CreateResourcesModule(libname);

  MENU_ID(IDR_LIBID)
  MENU_ID(CM_LINE_DIMM)
  MENU_ID(CM_DIM_COLLECTION)
  MENU_ID(CM_CHANGE_LINE_DIMM)
  MENU_ID(CM_RADIAL_DIMM)
  MENU_ID(CM_DIAM_DIMM)
  MENU_ID(CM_ANGLE_DIMM)
  MENU_ID(CM_ARC_DIMM)
  MENU_ID(CM_BREAK_LINE_DIMM)
  MENU_ID(CM_BREAK_RADIAL_DIMM)
  MENU_ID(CM_BREAK_ANGLE_DIMM)
  MENU_ID(CM_HEIGHT_DIMM)

  STRING_ID(IDR_LIBID)
  STRING_ID(IDS_NODOC)
  STRING_ID(IDS_COORDS)
  STRING_ID(IDS_DIM)
  STRING_ID(IDS_COMMAND1)
  STRING_ID(IDS_COMMAND2)
  STRING_ID(IDS_COMMAND3)
  STRING_ID(IDS_COMMAND4)
  STRING_ID(IDS_COMMAND5)
  STRING_ID(IDS_COMMAND6)
  STRING_ID(IDS_COMMAND7)
  STRING_ID(IDS_COMMAND8)
  STRING_ID(IDS_COMMAND9)
  STRING_ID(IDS_COMMAND10)
  STRING_ID(IDS_NOTDIM)
  STRING_ID(IDS_NOOBJ)
  STRING_ID(IDS_NOTCREATE1)
  STRING_ID(IDS_NOTCREATE2)
  STRING_ID(IDS_NOTCREATE3)
  STRING_ID(IDS_NOTCREATE4)
  STRING_ID(IDS_NOTCREATE5)
  STRING_ID(IDS_UNIT)
  STRING_ID(IDS_UNIT2)
  STRING_ID(IDS_NOMINAL)
  STRING_ID(IDS_EDIT)
  STRING_ID(IDS_NOOBJS)
  STRING_ID(IDS_ASK1)

  resourceModule->End();
}
