#include <KsAPI.h>

#include "Resource.h"
#include "SLIDE.RH"

using namespace ksapi;

static IResourcesModulePtr resourceModule;

void * GetModule()
{
  return &resourceModule;
}

#define MENU_ID(idName)     resourceModule->AddMenuId(L"" #idName, idName);
#define STRING_ID(idName)   resourceModule->AddStringId(L"" #idName, idName);
#define CURSOR_ID(idName)   resourceModule->AddCursourId(L"" #idName, idName);
#define RCDATA_ID(idName)   resourceModule->AddRCDataId(L"" #idName, idName);
#define UNUNIQUE_ID(idName) resourceModule->AddUnuniqueId(L"" #idName, idName);

void LoadResources(IApplication & app)
{
  resourceModule = app.CreateResourcesModule(L"Studs3D1");

  STRING_ID(ID_PROP_SCREW_ENDING_LENGHT)
  STRING_ID(IDS_SCREW_ENDING_TIPS)
  STRING_ID(ID_PROP_ISP)
  STRING_ID(IDS_ISP_TIPS)
  STRING_ID(IDS_ISP_HINT)
  STRING_ID(IDP_BMP_G_I1)
  STRING_ID(IDP_BMP_G_I2)
  STRING_ID(ID_PROP_CLASS)
  STRING_ID(IDS_CLASS_TIPS)
  STRING_ID(ID_PROP_GOST)
  STRING_ID(IDS_GOST_TIPS)
  STRING_ID(ID_PROP_MATERIAL)
  STRING_ID(IDS_MATERIAL_TIPS)

  STRING_ID(IDP_SPC_OBJ)
  STRING_ID(IDS_SPC_OBJ_TIPS)
  STRING_ID(ID_PROP_MASSA_1000)
  STRING_ID(ID_PROP_FACET)
  STRING_ID(ID_PROP_PITCH)
  STRING_ID(ID_PROP_SCREW_ENDING)
  STRING_ID(ID_PROP_WRENCH_ENDING)
  STRING_ID(ID_PROP_SIMPLE)
  STRING_ID(ID_PROP_G_STEP)
  STRING_ID(IDP_FLAGS)
  STRING_ID(IDS_FLAGS_TIPS)
  STRING_ID(ID_PROP_DIAM)
  STRING_ID(IDS_DIAM_TIPS)
  STRING_ID(ID_PROP_LENGHT)
  STRING_ID(IDS_LENGHT_TIPS)
  STRING_ID(ID_PROP_OTHER_PARAM)
  STRING_ID(ID_POINT_3D)

  STRING_ID(IDS_3DDOCERROR)
  STRING_ID(IDS_STUD_NAME)
  STRING_ID(STR_SELECT_PLANE)
  STRING_ID(STR_SELECT_POINT)

  STRING_ID(ID_DB_NOT_FOUND_ERROR)
  STRING_ID(ID_DB_ERROR)

  STRING_ID(STUDS_COMMAND)
  STRING_ID(STR_101)
  STRING_ID(STR_102)
  STRING_ID(STR_103)
  STRING_ID(STR_104)
  STRING_ID(STR_105)
  STRING_ID(STR_106)
  STRING_ID(STR_107)
  STRING_ID(STR_108)
  STRING_ID(STR_109)
  STRING_ID(STR_110)
  STRING_ID(STR_111)
  STRING_ID(STR_112)

  STRING_ID(STR_200)
  STRING_ID(STR_201)
  STRING_ID(STR_202)
  STRING_ID(STR_203)
  STRING_ID(STR_204)
  STRING_ID(STR_205)
  STRING_ID(STR_206)
  STRING_ID(STR_207)

  STRING_ID(STR_208)
  STRING_ID(STR_209)
  STRING_ID(STR_210)
  STRING_ID(STR_211)
  STRING_ID(STR_220)
  STRING_ID(STR_221)
  STRING_ID(STR_222)
  STRING_ID(STR_223)

  STRING_ID(STR_224)
  STRING_ID(STR_225)
  STRING_ID(STR_226)
  STRING_ID(STR_227)
  STRING_ID(STR_228)
  STRING_ID(STR_229)
  STRING_ID(STR_230)
  STRING_ID(STR_231)

  STRING_ID(IDP_STUDS)
  STRING_ID(ID_PROP_ELEMENT_PARAM)
  STRING_ID(IDS_PARAM_CAPTION)
  STRING_ID(IDS_VALUE_CAPTION)
  STRING_ID(IDS_STUD_1D)
  STRING_ID(IDS_STUD_125D)
  STRING_ID(IDS_STUD_16D)
  STRING_ID(IDS_STUD_2D)
  STRING_ID(IDS_STUD_25D)
  STRING_ID(IDS_STUD_B0)
  STRING_ID(IDS_STUD_A)
  STRING_ID(IDS_STUD_B)
  STRING_ID(IDS_MATERIAL_STEEL)
  STRING_ID(IDS_MATERIAL_ALUMINIUM)
  STRING_ID(IDS_MATERIAL_BRASS)
  STRING_ID(IDS_MATERIAL_BRONZE)

  STRING_ID(IDS_TAKE_POINT)

  UNUNIQUE_ID(END_SLIDE)
  UNUNIQUE_ID(LN)
  UNUNIQUE_ID(LS)
  UNUNIQUE_ID(SC)
  UNUNIQUE_ID(MA)
  UNUNIQUE_ID(AR1)
  UNUNIQUE_ID(TX)
  UNUNIQUE_ID(TS)
  UNUNIQUE_ID(CR)
  UNUNIQUE_ID(GB)

  RCDATA_ID(STUDS_COMMAND)
  RCDATA_ID(SH22042_1)
  RCDATA_ID(SH22042_2)
  RCDATA_ID(SH22042_3)
  RCDATA_ID(SH22032_1)
  RCDATA_ID(SH22032_2)
  RCDATA_ID(SH22032_3)

  resourceModule->End();
}
